import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadDeployDefaults } from '../config/deploy-defaults.js';
import { UserSkillStore, isUserSkillMode, parseUserSkillId, userSkillMode } from './user-skill-store.js';
import { getOrganizationSkillDef, listOrganizationSkillDefs, parseOrgSkillId } from './organization-skill-store.js';

export interface SkillDef { label: string; mode: string; feature?: string; brand_files: string[]; bundle_files: string[]; pipeline_script?: string; }
interface SkillsManifest { version: number; skills: Record<string, SkillDef>; }
const MAX_PROMPT_CHARS = 120_000;
export { MAX_PROMPT_CHARS };
export interface SkillListItem { id: string; label: string; mode: string; source: 'bundled' | 'user' | 'organization'; editable: boolean; removable?: boolean; install_kind?: 'prompt' | 'package'; description?: string; file_count?: number; feature?: string; selectable?: boolean; selector_group?: string; selector_order?: number; }
function defaultsDir(): string { const here = path.dirname(fileURLToPath(import.meta.url)); const candidates = [path.join(here, '..', '..', 'config', 'defaults'), path.join(here, '..', 'config', 'defaults'), path.join(here, 'config', 'defaults')]; for (const p of candidates) if (existsSync(path.join(p, 'skills', 'manifest.json'))) return p; return candidates[0]; }
export function resolveOrganizationModuleRoot(cqrRoot: string): string | null { const env = process.env.MY_AGENT_ORGANIZATION_MODULE_ROOT?.trim(); if (env && existsSync(env)) return path.resolve(env); const bundled = path.join(cqrRoot, 'modules', 'organization'); if (existsSync(bundled)) return path.resolve(bundled); const configured = loadDeployDefaults(cqrRoot).organization_module_root?.trim(); return configured && existsSync(configured) ? path.resolve(configured) : null; }
function loadManifest(): SkillsManifest { const p = path.join(defaultsDir(), 'skills', 'manifest.json'); return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) as SkillsManifest : { version: 1, skills: {} }; }
function readPromptFile(p: string): string | null { if (!existsSync(p)) return null; try { return readFileSync(p, 'utf8').trim(); } catch { return null; } }
export function getSkillDef(id: string): SkillDef | null { return loadManifest().skills[id] ?? null; }
export function loadSkillPromptParts(def: SkillDef, cqrRoot: string): { parts: string[]; sources: string[] } { const root = resolveOrganizationModuleRoot(cqrRoot); const defaults = defaultsDir(); const parts: string[] = []; const sources: string[] = []; const n = Math.max(def.brand_files.length, def.bundle_files.length); for (let i=0;i<n;i++) { let text: string | null = null; let source=''; if (root && def.brand_files[i]) { text=readPromptFile(path.join(root, def.brand_files[i])); if(text) source=`brand:${def.brand_files[i]}`; } if(!text && def.bundle_files[i]) { text=readPromptFile(path.join(defaults, def.bundle_files[i])); if(text) source=`bundle:${def.bundle_files[i]}`; } if(text){parts.push(text);sources.push(source);} } return {parts,sources}; }
export function getSkillSystemPrompt(id: string, cqrRoot: string, opts?: {tier?: 'slim'|'full'}): string | null { const def=getSkillDef(id); if(!def)return null; const {parts}=loadSkillPromptParts(def,cqrRoot); if(!parts.length)return null; return parts.join('\n\n---\n\n').slice(0,MAX_PROMPT_CHARS); }
export function getSkillMode(id: string): string | null { return getSkillDef(id)?.mode ?? null; }
export function listSkillModes(): string[] { return Object.values(loadManifest().skills).map(s=>s.mode); }
export function skillIdForMode(mode: string): string | null { return Object.entries(loadManifest().skills).find(([,s])=>s.mode===mode)?.[0] ?? null; }
export function resolvePipelineScript(id: string,cqrRoot:string):string|null { const def=getSkillDef(id); const root=resolveOrganizationModuleRoot(cqrRoot); if(!def?.pipeline_script||!root)return null; const p=path.join(root,def.pipeline_script); return existsSync(p)?p:null; }
function userSkillStore(cqrRoot:string):UserSkillStore{return new UserSkillStore(path.join(cqrRoot,'data','skills'),cqrRoot);}
export function listBundledSkills():SkillListItem[]{return Object.entries(loadManifest().skills).map(([id,def])=>({id,label:def.label,mode:def.mode,source:'bundled',editable:false,feature:def.feature}));}
function organizationSkills(cqrRoot:string):SkillListItem[]{return listOrganizationSkillDefs(cqrRoot).map(({id,def})=>({id,label:def.label,mode:def.mode,source:'organization',editable:false,feature:def.feature,selectable:def.user_selectable===true,selector_group:def.selector_group,selector_order:def.selector_order,description:def.selector_description}));}
export function listAllSkills(cqrRoot:string):SkillListItem[]{const user=userSkillStore(cqrRoot).list().map(rec=>({id:rec.id,label:rec.label,mode:userSkillMode(rec.id),source:'user' as const,editable:rec.install_kind!=='package',removable:true,install_kind:rec.install_kind??'prompt',description:rec.description,file_count:rec.file_count}));return [...listBundledSkills(),...user,...organizationSkills(cqrRoot)];}
export function listSelectableOrganizationSkills(cqrRoot:string):SkillListItem[]{return organizationSkills(cqrRoot).filter(s=>s.selectable).sort((a,b)=>(a.selector_order??Number.MAX_SAFE_INTEGER)-(b.selector_order??Number.MAX_SAFE_INTEGER));}
export function isBundledSkillId(id:string):boolean{return getSkillDef(id)!==null;}
export function getSkillSystemPromptByMode(mode:string,cqrRoot:string,opts?:{tier?:'slim'|'full'}):string|null { if(isUserSkillMode(mode)){const id=parseUserSkillId(mode);return id?userSkillStore(cqrRoot).readPrompt(id):null;} const orgId=parseOrgSkillId(mode); if(orgId){const def=getOrganizationSkillDef(orgId,cqrRoot);if(!def)return null;const {parts}=loadSkillPromptParts(def as SkillDef,cqrRoot);return parts.length?parts.join('\n\n---\n\n').slice(0,MAX_PROMPT_CHARS):null;} const id=skillIdForMode(mode);return id?getSkillSystemPrompt(id,cqrRoot,opts):null; }
